{
    'name': 'ESS',
    'version': '13.0.1.0',
    'author': 'Mr.Warrag - Telenoc',
    'images': ['static/description/app_logo.jpg'],
    'license': 'OPL-1',
    'category':  'Website',
    'depends': ['base', 'portal', 'website', 'account', 'hr_employee_letter', 'hr_payroll', 'Employee_Training', 'hr_appraisal'],
    'data': [
        'views/portal_templates.xml',
        'views/portal_network_directory.xml',
        'views/portal_leaves.xml',
        'views/portal_leaves_history.xml',
        'views/portal_leaves_balance.xml',
        'views/portal_leaves_track.xml',
        'views/portal_leaves_short.xml',
        'views/portal_allocation.xml',
        'views/portal_appraisal.xml',
        'views/portal_appraisal_request.xml',
        'views/portal_appraisal_trackt.xml',
        'views/portal_attendance.xml',
        'views/portal_document.xml',
        'views/portal_document_view.xml',
        'views/portal_loan.xml',
        'views/portal_loan_report.xml',
        'views/portal_loan_installments.xml',
        'views/portal_loan_track.xml',
        'views/portal_profile_view.xml',
        'views/portal_tasks.xml',
        'views/portal_announcement.xml',
        'views/portal_expenses.xml',
        'views/portal_expenses_track.xml',
        'views/portal_statment.xml',
        'views/portal_traning.xml',
        'views/portal_traning_my_courses.xml',
        'views/portal_traning_track.xml',
        'views/portal_letter.xml',
        'views/portal_letter_track.xml',
        'views/portal_petty_cash.xml',
        'views/portal_petty_cash_track.xml',
        'views/portal_document_company_ownered_view.xml',
        'views/portal_document_company_my_request.xml',
        'views/portal_document_company_requested.xml',
        'views/portal_profile_experians.xml',
        'views/portal_payslip.xml',
        'views/portal_payslip_correction_request.xml',
        'views/portal_payslip_correction_track.xml',
        'views/portal_eos.xml',
        'views/portal_profile_skills.xml',
        'views/portal_profile_education.xml',
        'views/portal_profile_contract.xml',
        'views/portal.xml',
        'report/partner_ledger_report.xml',
        'report/partner_ledger_report_template.xml',
        'data/access.xml',
    ],
    'qweb': [
    ],
    'installable': True,
    'auto_install': False,
}
